# Generated by OmopViewer 0.6.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_person = FALSE,
    summarise_device_exposure = FALSE,
    summarise_implant_type = FALSE,
    summarise_procedures = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )
  # summarise_person -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_person <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_person_cdm_name,
      input$summarise_person_variable_name,
      input$summarise_person_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_person, {
    if (updateButtons$summarise_person == TRUE) {
      output$update_message_summarise_person <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_person <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_person, {
    updateButtons$summarise_person <- FALSE
  })

  ## get summarise_person data
  getSummarisePersonData <- shiny::eventReactive(input$update_summarise_person, {
    data[["summarise_person"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_person_cdm_name,
        .data$variable_name %in% input$summarise_person_variable_name,
        .data$estimate_name %in% input$summarise_person_estimate_name
      )
  })
  getSummarisePersonTable <- shiny::reactive({
    getSummarisePersonData() |>
      OmopSketch::tablePerson()
  })
  output$summarise_person_table <- gt::render_gt({
    getSummarisePersonTable()
  })
  output$summarise_person_table_download <- shiny::downloadHandler(
    filename = paste0("table_person.", input$summarise_person_table_format),
    content = function(file) {
      gt::gtsave(getSummarisePersonTable(), file)
    }
  )
  getSummarisePersonPlot <- shiny::reactive({
    getSummarisePersonData() |>
      OmopSketch::plotPerson(
        variableName = input$summarise_person_plot_variable
      )
  })
  output$summarise_person_plot <- shiny::renderUI({
    x <- getSummarisePersonPlot()
    renderInteractivePlot(x, input$summarise_person_plot_interactive)
  })
  output$summarise_person_plot_download <- shiny::downloadHandler(
    filename = "plot_person.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummarisePersonPlot(),
        width = as.numeric(input$summarise_person_plot_width),
        height = as.numeric(input$summarise_person_plot_height),
        units = input$summarise_person_plot_units,
        dpi = as.numeric(input$summarise_person_plot_dpi)
      )
    }
  )
  # summarise_device_exposure -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_device_exposure <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_device_exposure_cdm_name,
      input$summarise_device_exposure_omop_table,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_device_exposure, {
    if (updateButtons$summarise_device_exposure == TRUE) {
      output$update_message_summarise_device_exposure <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_device_exposure <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_device_exposure, {
    updateButtons$summarise_device_exposure <- FALSE
  })

  ## get summarise_device_exposure data ----
  getSummariseDeviceExposureData <- shiny::eventReactive(input$update_summarise_device_exposure, {
    data[["summarise_device_exposure"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_device_exposure_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_device_exposure_omop_table)
  })
  getSummariseDeviceExposureTable <- shiny::reactive({
    getSummariseDeviceExposureData() |>
      OmopSketch::tableClinicalRecords()
  })
  output$summarise_device_exposure_table <- gt::render_gt({
    getSummariseDeviceExposureTable()
  })
  output$summarise_device_exposure_table_download <- shiny::downloadHandler(
    filename = paste0("table_clinical_records.", input$summarise_device_exposure_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDeviceExposureTable(), file)
    }
  )
  
  # summarise_code_use -----
  shiny::observe({
    updateButtons$summarise_code_use <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_code_use_cdm_name,
      input$summarise_code_use_cohort_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_code_use, {
    if (updateButtons$summarise_code_use == TRUE) {
      output$update_message_summarise_code_use <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_summarise_code_use <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_code_use, {
    updateButtons$summarise_code_use <- FALSE
  })
  
  getSummariseCodeUseData <- shiny::eventReactive(input$update_summarise_code_use, {
    data[["summarise_code_use"]] |>
      dplyr::filter(variable_level != "overall") |>
      dplyr::filter(.data$cdm_name %in% input$summarise_code_use_cdm_name,
                    .data$estimate_name %in% input$summarise_code_use_estimate_name,
                    .data$variable_name %in% input$summarise_code_use_variable_name,
                    .data$strata_level %in% input$summarise_code_use_year) 
  })
  getSummariseCodeUseTable <- shiny::reactive({
    getSummariseCodeUseData()  |>
      CodelistGenerator::tableCodeUse(type = "reactable", 
                                      header = as.character(),
                                      hide = c("codelist_name", "source_concept_name", 
                                               "source_concept_id", "type_concept_id", 
                                               "domain_id", "table", "source_concept_value",
                                               "type_concept_name", "date_range_end", "date_range_start"), 
                                      groupColumn = "cdm_name")
  })
  output$summarise_code_use_table <- shiny::renderUI({
    getSummariseCodeUseTable()
  })
  output$summarise_code_use_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_code_use_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresToDevicesTable(), file)
    }
  )
  getSummariseCodeUsePlot <- shiny::reactive({
    
    getSummariseCodeUseData()  |>
      visOmopResults::scatterPlot(x = "year",
                                  y = input$summarise_code_use_estimate_name, 
                                  line = FALSE, point = TRUE, ribbon = FALSE, 
                                  facet = input$summarise_code_use_plot_facet, 
                                  colour = input$summarise_code_use_plot_colour)
    
  })
  output$summarise_code_use_plot <- shiny::renderUI({
    x <- getSummariseCodeUsePlot()
    renderInteractivePlot(x, input$summarise_code_use_plot_interactive)
  })
  output$summarise_code_use_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCodeUsePlot(),
        width = as.numeric(input$summarise_code_use_plot_width),
        height = as.numeric(input$summarise_code_use_plot_height),
        units = input$summarise_code_use_plot_units,
        dpi = as.numeric(input$summarise_code_use_plot_dpi)
      )
    }
  )
  
  # summarise_devices_to_procedures -----
  shiny::observe({
    updateButtons$summarise_devices_to_procedures <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_devices_to_procedures_cdm_name,
      input$summarise_devices_to_procedures_cohort_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_devices_to_procedures, {
    if (updateButtons$summarise_devices_to_procedures == TRUE) {
      output$update_message_summarise_devices_to_procedures <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_summarise_devices_to_procedures <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_devices_to_procedures, {
    updateButtons$summarise_devices_to_procedures <- FALSE
  })
  
  getSummariseDevicesToProceduresData <- shiny::eventReactive(input$update_summarise_devices_to_procedures, {
    data[["summarise_devices_to_procedures"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_devices_to_procedures_cdm_name,
        .data$estimate_name %in% c("count", "percentage")
      ) |>
      mutate("group_level" = str_to_sentence(gsub("_", " ", group_level))) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_devices_to_procedures_cohort_name) |>
      visOmopResults::splitAdditional(keep = TRUE) |>
      mutate(group_level = if_else(group_level == "no_matching_concept", 
                                   "No matching concept", 
                                   paste0(stringr::str_to_sentence(gsub("_"," ",group_level)), " (", device_concept_id, ")"))) |>
      dplyr::mutate("variable_name" = if_else(grepl("Proc", variable_name),
                                               "Procedures",
                                               variable_name)) |>
       dplyr::mutate("variable_level" = if_else(grepl("Procedures", variable_name),
                                              paste0(procedure_concept_name, " (", procedure_concept_id, ")"),
                                              variable_name)) |>
      select(-c("device_concept_id", "procedure_concept_id", "procedure_concept_name")) |>
      mutate("new_col" = case_when(
        variable_name %in% c("Number subjects", "Number records") ~ 200,
        estimate_name == "percentage" ~ as.numeric(estimate_value),
        .default = NA
      )) |>
      arrange(group_level, desc(new_col)) |>
      select(-"new_col")
  })
  getSummariseDevicesToProceduresTable <- shiny::reactive({
    getSummariseDevicesToProceduresData() |>
      tableCharacteristics(
        groupColumn = input$summarise_devices_to_procedures_table_group_column,
        header = input$summarise_devices_to_procedures_table_header,
        hide = c("device_concept_id", "device_concept_name", "procedure_concept_id", "procedure_concept_name", input$summarise_devices_to_procedures_table_hide)
      )
  })
  output$summarise_devices_to_procedures_table <- gt::render_gt({
    getSummariseDevicesToProceduresTable()
  })
  output$summarise_devices_to_procedures_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_devices_to_procedures_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresToDevicesTable(), file)
    }
  )
  getSummariseDevicesToProceduresPlot <- shiny::reactive({
    getSummariseDevicesToProceduresData() |>
      filter(variable_name == "Procedures") |>
      filter(estimate_name == input$summarise_devices_to_procedures_estimate_name) |>
      mutate(additional_name = "overall",
             additional_level = "overall") |>
      filter(estimate_value != "-") |>
      CohortCharacteristics::plotCharacteristics(
        plotType = "barplot",
        facet = input$summarise_devices_to_procedures_plot_facet,
        colour = input$summarise_devices_to_procedures_plot_colour,
      ) +
      geom_col(
        aes(color = after_scale(scales::muted(fill))),
        linewidth = 0.3,
        show.legend = FALSE
      ) +
      coord_flip() +
      theme_bw() +
      theme(legend.position = "top") + 
      labs(color = NULL, fill = NULL, 
           x = "Procedures", 
           y = str_to_sentence(input$summarise_devices_to_procedures_estimate_name)) +
      guides(color = "none")
  })
  output$summarise_devices_to_procedures_plot <- shiny::renderUI({
    x <- getSummariseDevicesToProceduresPlot()
    renderInteractivePlot(x, input$summarise_devices_to_procedures_plot_interactive)
  })
  output$summarise_devices_to_procedures_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseDevicesToProceduresPlot(),
        width = as.numeric(input$summarise_devices_to_procedures_plot_width),
        height = as.numeric(input$summarise_devices_to_procedures_plot_height),
        units = input$summarise_devices_to_procedures_plot_units,
        dpi = as.numeric(input$summarise_devices_to_procedures_plot_dpi)
      )
    }
  )
  ## summarise udi ----
  shiny::observe({
    updateButtons$summarise_udi <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_udi_cdm_name,
      input$summarise_udi_cohort_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_udi, {
    if (updateButtons$summarise_udi == TRUE) {
      output$update_message_summarise_udi <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_summarise_udi <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_udi, {
    updateButtons$summarise_udi <- FALSE
  })
  
  getSummariseUdiData <- shiny::eventReactive(input$update_summarise_udi, {
    data[["summarise_udi"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_udi_cdm_name) |>
      mutate("group_level" = str_to_sentence(gsub("_", " ", group_level))) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_udi_cohort_name) |>
      visOmopResults::splitAdditional(keep = TRUE) |>
      mutate(group_level = if_else(group_level == "no_matching_concept", "No matching concept", paste0(stringr::str_to_sentence(gsub("_"," ",group_level)), " (", device_concept_id, ")"))) |>
      dplyr::mutate("variable_name" = if_else(grepl("Value", variable_name),
                                              "Unique Device Identifier",
                                              variable_name)) |>
      dplyr::mutate("variable_level" = case_when(
        variable_level == "0" ~ "Not available",
        variable_level == "1" ~ "Available",
        .default = variable_level)) |>
      select(-c("device_concept_id")) |>
      mutate("new_col" = case_when(
        variable_name %in% c("Number subjects", "Number records") ~ 200,
        estimate_name == "percentage" ~ as.numeric(estimate_value),
        .default = NA
      )) |>
      arrange(group_level, desc(new_col)) |>
      select(-"new_col")
  })
  getSummariseUdiTable <- shiny::reactive({
    getSummariseUdiData() |>
      tableCharacteristics(
        groupColumn = input$summarise_udi_table_group_column,
        header = input$summarise_udi_table_header,
        hide = c("device_concept_id", "device_concept_name", "procedure_concept_id", "procedure_concept_name", input$summarise_udi_table_hide)
      )
  })
  output$summarise_udi_table <- gt::render_gt({
    getSummariseUdiTable()
  })
  output$summarise_udi_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_udi_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresToDevicesTable(), file)
    }
  )
  getSummariseUdiPlot <- shiny::reactive({
    getSummariseUdiData() |>
      filter(variable_name == "Unique Device Identifier") |>
      filter(estimate_name == input$summarise_udi_estimate_name) |>
      mutate(additional_name = "overall",
             additional_level = "overall") |>
      filter(estimate_value != "-") |>
      visOmopResults::barPlot(
        x = "cohort_name",
        y = input$summarise_udi_estimate_name,
        position = "stack",
        facet = input$summarise_udi_facet,
        colour = "variable_level"
      ) +
      ggplot2::scale_fill_manual(values = c("Available" = "#FFAD0AFF", "Not available" = "#A9A9A9")) +
      ggplot2::scale_colour_manual(values = c("Available" = "#C68600", "Not available" = "#6B6B6B")) +
      coord_flip() +
      theme_bw() +
      theme(legend.position = "top") + 
      labs(color = NULL, fill = NULL, 
           x = "Concept Name (ID)", 
           y = str_to_sentence(input$summarise_udi_estimate_name)) +
      guides(color = "none")
  })
  output$summarise_udi_plot <- shiny::renderUI({
    x <- getSummariseUdiPlot()
    renderInteractivePlot(x, input$summarise_udi_plot_interactive)
  })
  output$summarise_udi_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseUdiPlot(),
        width = as.numeric(input$summarise_udi_plot_width),
        height = as.numeric(input$summarise_udi_plot_height),
        units = input$summarise_udi_plot_units,
        dpi = as.numeric(input$summarise_udi_plot_dpi)
      )
    }
  )
  
  
  # # summarise_implant_type -----
  # ## update message if filter is changed
  # shiny::observe({
  #   updateButtons$summarise_implant_type <- TRUE
  # }) |>
  #   shiny::bindEvent(
  #     input$summarise_implant_type_cdm_name,
  #     input$summarise_implant_type_cohort_name,
  #     input$summarise_implant_type_variable_name,
  #     ignoreInit = TRUE
  #   )
  # shiny::observeEvent(updateButtons$summarise_implant_type, {
  #   if (updateButtons$summarise_implant_type == TRUE) {
  #     output$update_message_summarise_implant_type <- shiny::renderUI(updateMessage) # defined in functions.R
  #   } else {
  #     output$update_message_summarise_implant_type <- shiny::renderUI(NULL)
  #   }
  # })
  # shiny::observeEvent(input$update_summarise_implant_type, {
  #   updateButtons$summarise_implant_type <- FALSE
  # })
  # 
  # ## get summarise_implant_type data
  # getSummariseImplantTypeData <- shiny::eventReactive(input$update_summarise_implant_type, {
  #  data[["summarise_implant_type"]] |>
  #     dplyr::filter(
  #       .data$variable_name %in% c("Number records", "Number subjects", "Device concept id"),
  #       .data$cdm_name %in% input$summarise_implant_type_cdm_name
  #     ) |>
  #     dplyr::mutate("variable_name" = gsub("Device concept id", "Device Concept Name (Concept ID)", .data$variable_name)) |>
  #     dplyr::mutate("variable_level" = if_else(
  #       .data$variable_name %in% c("Number records", "Number subjects"),
  #       .data$variable_level,
  #       paste0(.data$additional_level, " (", .data$variable_level,")")
  #     )) |>
  #     omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_implant_type_cohort_name) |>
  #     mutate("variable_name" = factor(.data$variable_name, levels = c("Number records", "Number subjects", "Device Concept Name (Concept ID)"))) |>
  #     mutate("new_var" = if_else(estimate_name == "percentage", as.numeric(.data$estimate_value), NA)) |>
  #     arrange(group_level, variable_name, desc(new_var)) |>
  #     select(-"new_var")
  # })
  # getSummariseImplantTypeTable <- shiny::reactive({
  #   getSummariseImplantTypeData() |>
  #     CohortCharacteristics::tableCharacteristics(
  #       header = input$summarise_implant_type_table_header,
  #       groupColumn = input$summarise_implant_type_table_group_column,
  #       hide = input$summarise_implant_type_table_hide
  #     )
  # })
  # output$summarise_implant_type_table <- gt::render_gt({
  #   getSummariseImplantTypeTable()
  # })
  # output$summarise_implant_type_table_download <- shiny::downloadHandler(
  #   filename = paste0("table_characteristics.", input$summarise_implant_type_table_format),
  #   content = function(file) {
  #     gt::gtsave(getSummariseImplantTypeTable(), file)
  #   }
  # )
  # getSummariseImplantTypePlot <- shiny::reactive({
  #   getSummariseImplantTypeData() |>
  #     dplyr::filter(.data$variable_name %in% c("Device Concept Name (Concept ID)")) |>
  #     dplyr::filter(.data$estimate_name %in% input$summarise_implant_type_plot_vertical_axis) |>
  #     CohortCharacteristics::plotCharacteristics(
  #       plotType = "barplot",
  #       facet = input$summarise_implant_type_plot_facet,
  #       colour = input$summarise_implant_type_plot_colour
  #     ) + 
  #     coord_flip()
  # })
  # output$summarise_implant_type_plot <- shiny::renderUI({
  #   x <- getSummariseImplantTypePlot()
  #   renderInteractivePlot(x, input$summarise_implant_type_plot_interactive)
  # })
  # output$summarise_implant_type_plot_download <- shiny::downloadHandler(
  #   filename = "plot_characteristics.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = getSummariseImplantTypePlot(),
  #       width = as.numeric(input$summarise_implant_type_plot_width),
  #       height = as.numeric(input$summarise_implant_type_plot_height),
  #       units = input$summarise_implant_type_plot_units,
  #       dpi = as.numeric(input$summarise_implant_type_plot_dpi)
  #     )
  #   }
  # )
  # summarise_procedures_to_devices -----
  shiny::observe({
    updateButtons$summarise_procedures_to_devices <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_procedures_to_devices_cdm_name,
      input$summarise_procedures_to_devices_cohort_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_procedures_to_devices, {
    if (updateButtons$summarise_procedures_to_devices == TRUE) {
      output$update_message_summarise_procedures_to_devices <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_summarise_procedures_to_devices <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_procedures_to_devices, {
    updateButtons$summarise_procedures_to_devices <- FALSE
  })

  getSummariseProceduresToDevicesData <- shiny::eventReactive(input$update_summarise_procedures_to_devices, {
    data[["summarise_procedures_to_devices"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_procedures_to_devices_cdm_name,
        .data$estimate_name %in% c("count", "percentage")
      ) |>
      visOmopResults::splitAdditional(keep = TRUE) |>
      mutate("group_name" = "cohort_name",
             "group_level" = case_when(
               group_level == "pda_division" ~ "Division of Patent Ductus Arteriosus",
               group_level == "pda_ligature" ~ "Ligature of Patent Ductus Arteriosus",
               group_level == "pda_closure" ~ "Closure of Patent Ductus Arteriosus (With Prosthesis)",
               group_level == "fluoroscopy"  ~ "Fluoroscopy",
               group_level == "surgery" ~ "Surgery")) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_procedures_to_devices_cohort_name) |>
      dplyr::mutate("variable_level" = case_when(
        variable_name %in% c("Number records", "Number subjects") ~ variable_name,
        variable_name %in% c("Dev -1", "Dev 0") ~ device_concept_name,
        .default = paste0(device_concept_name, " (", device_concept_id, ")")
      )) |>
      dplyr::mutate("variable_name" = case_when(
        variable_name %in% c("Number records", "Number subjects") ~ variable_name,
        .default = "Devices"
      )) |>
      select(-c("device_concept_id", "device_concept_name")) |>
      mutate("new_col" = case_when(
        variable_name %in% c("Number subjects", "Number records") ~ 200,
        estimate_name == "percentage" ~ as.numeric(estimate_value),
        .default = NA
      )) |>
      arrange(group_level, desc(new_col)) |>
      select(-"new_col")
  })
  getSummariseProceduresToDevicesTable <- shiny::reactive({
    getSummariseProceduresToDevicesData() |>
      tableCharacteristics(
        groupColumn = input$summarise_procedures_to_devices_table_group_column,
        header = input$summarise_procedures_to_devices_table_header,
        hide = c("device_concept_id", "device_concept_name", input$summarise_procedures_to_devices_table_hide)
      )
  })
  output$summarise_procedures_to_devices_table <- gt::render_gt({
    getSummariseProceduresToDevicesTable()
  })
  output$summarise_procedures_to_devices_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_procedures_to_devices_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProceduresToDevicesTable(), file)
    }
  )
  getSummariseProceduresToDevicesPlot <- shiny::reactive({

    getSummariseProceduresToDevicesData()  |>
      filter(variable_name == "Devices") |>
      filter(estimate_name == input$summarise_devices_to_procedures_estimate_name) |>
      mutate(additional_name = "overall",
             additional_level = "overall") |>
      filter(estimate_value != "-") |>
      CohortCharacteristics::plotCharacteristics(
        plotType = "barplot",
        facet = input$summarise_procedures_to_devices_plot_facet,
        colour = input$summarise_procedures_to_devices_plot_colour
      ) +
      geom_col(
        aes(color = after_scale(scales::muted(fill))),
        linewidth = 0.3,
        show.legend = FALSE
      ) +
      coord_flip() +
      theme_bw() +
      theme(legend.position = "top") + 
      labs(color = NULL, fill = NULL, 
           x = "Devices", 
           y = str_to_sentence(input$summarise_procedures_to_devices_estimate_name)) +
      guides(color = "none")
  })
  output$summarise_procedures_to_devices_plot <- shiny::renderUI({
    x <- getSummariseProceduresToDevicesPlot()
    renderInteractivePlot(x, input$summarise_procedures_to_devices_plot_interactive)
  })
  output$summarise_procedures_to_devices_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseProceduresToDevicesPlot(),
        width = as.numeric(input$summarise_procedures_to_devices_plot_width),
        height = as.numeric(input$summarise_procedures_to_devices_plot_height),
        units = input$summarise_procedures_to_devices_plot_units,
        dpi = as.numeric(input$summarise_procedures_to_devices_plot_dpi)
      )
    }
  )
  
  
}
