# Generated by OmopViewer 0.6.0
# Be careful editing this file

ui <- bslib::page_navbar(
  theme = bs_theme(5, "pulse", primary = "#325D88"),
  navbar_options =list(class = "bg-dark", theme = "dark"),
  
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hds_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
  ),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_menu(
    title = "Database Characteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Person Table Summary",
      icon = shiny::icon("person"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_person",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_person")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_person_cdm_name",
            label = "CDM name",
            choices = choices$summarise_person_cdm_name,
            selected = selected$summarise_person_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_person_variable_name",
            label = "Variable name",
            choices = choices$summarise_person_variable_name,
            selected = selected$summarise_person_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_person_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_person_estimate_name,
            selected = selected$summarise_person_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Person",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_person_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_person_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_person_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Person",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_person_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_person_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_person_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_person_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_person_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_person_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_person_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Number subjects not in observation", "Sex", "Sex source", "Race", "Race source", "Ethnicity", "Ethnicity source", "Year of birth", "Month of birth", "Day of birth", "Location", "Provider", "Care site"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_person_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period Summary",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_observation_period",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_observation_period")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Devices Summary",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Device Exposure Table",
      icon = shiny::icon("bars-staggered"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_device_exposure",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_device_exposure")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_device_exposure_cdm_name",
            label = "CDM name",
            choices = choices$summarise_device_exposure_cdm_name,
            selected = selected$summarise_device_exposure_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_device_exposure_omop_table",
            label = "Omop table",
            choices = choices$summarise_device_exposure_omop_table,
            selected = selected$summarise_device_exposure_omop_table,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Clinical records",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_device_exposure_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_device_exposure_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_device_exposure_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Devices counts",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = "18%",
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_code_use",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_code_use")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_code_use_cdm_name",
            label = "CDM name",
            choices = choices$summarise_code_use_cdm_name,
            selected = selected$summarise_code_use_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_code_use_variable_name",
            label = "Estimate",
            choices = choices$summarise_code_use_variable_name,
            selected = selected$summarise_code_use_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_code_use_year",
            label = "Year",
            choices = choices$summarise_code_use_year,
            selected = selected$summarise_code_use_year,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_code_use_estimate_name",
            label = "Estimate",
            choices = choices$summarise_code_use_estimate_name,
            selected = selected$summarise_code_use_estimate_name,
            multiple = FALSE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_code_use_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_code_use_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              shiny::uiOutput("summarise_code_use_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_code_use_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_code_use_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_code_use_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_code_use_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_code_use_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(open = "closed",
                                         shinyWidgets::materialSwitch(
                                           inputId = "summarise_code_use_plot_interactive",
                                           label = "Interactive",
                                           value = TRUE
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_code_use_estimate_name",
                                           label = "Estimate",
                                           choices = c("percentage", "count"),
                                           selected = "percentage",
                                           multiple = FALSE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_code_use_plot_facet",
                                           label = "Facet",
                                           choices = c("cdm_name", "variable_name"),
                                           selected = "cdm_name",
                                           multiple = TRUE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_code_use_plot_colour",
                                           label = "Colour",
                                           choices = c("cdm_name", "variable_name"),
                                           selected = "variable_name",
                                           multiple = TRUE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         position = "right"
                ),
                shiny::uiOutput("summarise_code_use_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      ## Devices to Procedures Summary
      title = "Procedures for each Device",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = "18%",
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_devices_to_procedures",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_devices_to_procedures")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_devices_to_procedures_cdm_name",
            label = "CDM name",
            choices = choices$summarise_devices_to_procedures_cdm_name,
            selected = selected$summarise_devices_to_procedures_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_devices_to_procedures_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_devices_to_procedures_cohort_name,
            selected = selected$summarise_devices_to_procedures_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_devices_to_procedures_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(open = "closed", 
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_devices_to_procedures_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name"),
                      input_id = "summarise_devices_to_procedures_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cohort_name"),
                      input_id = "summarise_devices_to_procedures_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_devices_to_procedures_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_devices_to_procedures_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_devices_to_procedures_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_devices_to_procedures_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_devices_to_procedures_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_devices_to_procedures_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(open = "closed",
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_devices_to_procedures_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_estimate_name",
                    label = "Estimate",
                    choices = c("percentage", "count"),
                    selected = "percentage",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_devices_to_procedures_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      ## UDI summary
      title = "UDIs Summary",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          width = "18%",
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_udi",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_udi")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_udi_cdm_name",
            label = "CDM name",
            choices = choices$summarise_udi_cdm_name,
            selected = selected$summarise_udi_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_udi_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_udi_cohort_name,
            selected = selected$summarise_udi_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_udi_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_udi_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(open = "closed", 
                                         sortable::bucket_list(
                                           header = NULL,
                                           sortable::add_rank_list(
                                             text = "None",
                                             labels = c("variable_name", "variable_level", "estimate_name"),
                                             input_id = "summarise_udi_table_none"
                                           ),
                                           sortable::add_rank_list(
                                             text = "Header",
                                             labels = c("cdm_name"),
                                             input_id = "summarise_udi_table_header"
                                           ),
                                           sortable::add_rank_list(
                                             text = "Group columns",
                                             labels = c("cohort_name"),
                                             input_id = "summarise_udi_table_group_column"
                                           ),
                                           sortable::add_rank_list(
                                             text = "Hide",
                                             labels = "table_name",
                                             input_id = "summarise_udi_table_hide"
                                           )
                                         ),
                                         position = "right"
                ),
                gt::gt_output("summarise_udi_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_udi_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_udi_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_udi_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_udi_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_udi_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(open = "closed",
                                         shinyWidgets::materialSwitch(
                                           inputId = "summarise_udi_plot_interactive",
                                           label = "Interactive",
                                           value = TRUE
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_udi_estimate_name",
                                           label = "Estimate",
                                           choices = c("percentage", "count"),
                                           selected = "percentage",
                                           multiple = FALSE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_udi_plot_facet",
                                           label = "Facet",
                                           choices = c("cdm_name", "cohort_name"),
                                           selected = "cdm_name",
                                           multiple = TRUE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         shinyWidgets::pickerInput(
                                           inputId = "summarise_udi_plot_colour",
                                           label = "Colour",
                                           choices = c("cdm_name", "cohort_name"),
                                           selected = "cohort_name",
                                           multiple = TRUE,
                                           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                                         ),
                                         position = "right"
                ),
                shiny::uiOutput("summarise_udi_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  # Procedures ----
  bslib::nav_menu(
    title = "Procedures Summary",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      ## Procedures to devices summary
      title = "Devices for each Procedure",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_procedures_to_devices",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_procedures_to_devices")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_to_devices_cdm_name",
            label = "CDM name",
            choices = choices$summarise_procedures_to_devices_cdm_name,
            selected = selected$summarise_procedures_to_devices_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_procedures_to_devices_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_procedures_to_devices_cohort_name,
            selected = selected$summarise_procedures_to_devices_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_to_devices_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_procedures_to_devices_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_procedures_to_devices_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name"),
                      input_id = "summarise_procedures_to_devices_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cohort_name"),
                      input_id = "summarise_procedures_to_devices_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_procedures_to_devices_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_procedures_to_devices_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_procedures_to_devices_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_procedures_to_devices_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_to_devices_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_procedures_to_devices_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_procedures_to_devices_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_procedures_to_devices_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_devices_to_procedures_estimate_name",
                    label = "Estimate",
                    choices = c("percentage", "count"),
                    selected = "percentage",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_procedures_to_devices_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_procedures_to_devices_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.6.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
